name: Create tag action
description: Format a deploy version tag for a git repository

runs:
  using: composite
  steps:
    - name: Create version tag (PR)  
      if: ${{ github.event_name == 'pull_request' }}  
      shell: bash 
      run: echo "tag=$(git show -s --format="%ct-%h" ${{ github.event.pull_request.head.sha }})" >> $GITHUB_ENV
    - name: Create version tag (Push)  
      if: ${{ github.event_name == 'push' }}  
      shell: bash
      run: echo "tag=$(git show -s --format="%ct-%h" ${GITHUB_SHA})" >> $GITHUB_ENV
